version: "3.1"
services:
  handle_service:
    image: kbase/handle_service:${TRAVIS_BRANCH:-develop}
    command: 
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "-env"
      - "https://gitlab.kbase.lbl.gov:1443/devops/serviceconf/raw/master/handle_service/handle_service-ci.yml"
      - "-env-header"
      - "/run/secrets/auth_data"
      - "-validate-cert=false"
      - "-wait"
      - "tcp://ci-mysql:3306"
      - "-timeout"
      - "150s"
      - "starman"
      - "--listen"
      - ":7109"
      - "/kb/deployment/lib/Bio/KBase/AbstractHandle/AbstractHandle.psgi"
    ports:
      - "7109:7109"
    environment:
      - KB_SERVICE_NAME=handle_service
    secrets:
      - auth_data
    depends_on: ["handle_manager", "ci-mysql"]

  mysqlinit:
    image: mysql:5.5
    volumes:
      - ./mysqldump:/mnt/mysqldump
    entrypoint: [ "mysql", "-h", "ci-mysql", "-e", "source /mnt/mysqldump"]
    depends_on: [ "ci-mysql" ]

  handle_manager:
    image: kbase/handle_mngr:latest
    command: 
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "-env"
      - "https://gitlab.kbase.lbl.gov:1443/devops/serviceconf/raw/master/handle_mngr/handle_mngr-ci.yml"
      - "-wait"
      - "tcp://auth2:8080"
      - "-timeout"
      - "120s"
      - "starman"
      - "--listen"
      - ":9001"
      - "/kb/deployment/lib/Bio/KBase/HandleMngr/HandleMngr.psgi"
    ports:
      - "9001:9001"
    secrets:
      - auth_data

  ci-mysql:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

# Authentication token for gitlab needs to be specified in the secrets file into the
# form "PRIVATE-TOKEN:GITLABTOKENSTRING" with no space after the colon, this sets an HTTP header
# of PRIVATE_TOKEN which will be used by the gitlab service endpoint for auth
secrets:
  auth_data:
    file: secrets/auth_data

